name: CI
on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      NuGetAPIKey: ${{ secrets.NuGetAPIKey }}
      ProjectName: WPFMaskedTextBox

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build
      shell: pwsh
      run: dotnet build -c Release

    - name: Push nuget packages if a new tag is pushed
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
      shell: pwsh
      run: |
        dotnet nuget push ${{ env.ProjectName }}\bin\Release\*.nupkg -s https://nuget.pkg.github.com/HMBSbige -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
        dotnet nuget push ${{ env.ProjectName }}\bin\Release\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NuGetAPIKey }} --skip-duplicate
